import type { Metadata } from "next"
import { Inter } from "next/font/google"
import "./globals.css"
import Navbar from "@/components/Navbar"
import { client } from "@/tina/__generated__/databaseClient"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const result = await client.queries.nav({
    relativePath: "header.mdx",
  })
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar {...JSON.parse(JSON.stringify(result))} />
        <main className="flex min-h-screen flex-col items-center justify-between p-24">
          {children}
        </main>
      </body>
    </html>
  )
}
